export const MandatorySubjects = [
  { value: "", label: "" },
  { value: "Makedonski jazik", label: "Македонски јазик" },
  { value: "Angliski jazik", label: "Англиски јазик" },
  { value: "Albanski jazik", label: "Албански јазик" },
  { value: "Turski jazik", label: "Турски јазик" },
  { value: "Vtor stranski jazik", label: "Втор странски јазик" },
  { value: "Matematika", label: "Математика" },
  { value: "Opsestvo", label: "Опшество" },
  { value: "Prirodni nauki", label: "Природни науки" },
  { value: "Muzicko obrazovanie", label: "Музичко образование" },
  { value: "Likovno obrazovanie", label: "Ликовно образование" },
  { value: "Tehnicko obrazovanie", label: "Техночко образование" },
  { value: "Geografija", label: "Географија" },
  { value: "Istorija", label: "Историја" },
  { value: "Biologija", label: "Биологија" },
  { value: "Hemija", label: "Хемија" },
  {
    value: "Rabota so kompjuteri i osnovi na programiranjeto",
    label: "Работа со компјутери и основи на програмирањето",
  },
  { value: "Informatika", label: "Информатика" },
  { value: "Etika", label: "Етика" },
  { value: "Gragjansko obrazovanie", label: "Граѓанско образование" },
  { value: "Fizika", label: "Физика" },
  { value: "Inovacii", label: "Иновации" },
  {
    value: "Fizicko i zdravstveno obrazovanie",
    label: "Физичко и здравствено образование",
  },
  { value: "Jazik i kultura na Vlasite", label: "Јазик и култура на Власите" },
  { value: "Jazik i kultura na Romite", label: "Јазик и култура на Ромите" },
  {
    value: "Jazik i kultura na Bosnjacite",
    label: "Јазик и култура на Бошњаците",
  },
  { value: "Jazik i kultura na Srbite", label: "Јазик и култура на Србите" },
  { value: "Jazik i kultura na Turcite", label: "Јазик и култура на Турците" },
  { value: "Tvorestvo", label: "Творештво" },
  { value: "Etika na religii", label: "Етика на религии" },
  { value: "Zapoznavanje na religiite", label: "Запознавање на религиите" },
  {
    value: "Klasicna kultura vo evropskata civilizacija",
    label: "Класична култура во европската цивилизација",
  },
  { value: "Albanski jazik", label: "Албански јазик" },
];

export const OptionalSubjects = [
  { value: "", label: "" },
  { value: "Jazik i kultura na Vlasite", label: "Јазик и култура на Власите" },
  { value: "Jazik i kultura na Romite", label: "Јазик и култура на Ромите" },
  {
    value: "Jazik i kultura na Bosnjacite",
    label: "Јазик и култура на Бошњаците",
  },
  { value: "Jazik i kultura na Srbite", label: "Јазик и култура на Србите" },
  { value: "Jazik i kultura na Turcite", label: "Јазик и култура на Турците" },
  { value: "Tvorestvo", label: "Творештво" },
  { value: "Etika na religii", label: "Етика на религии" },
  { value: "Zapoznavanje na religiite", label: "Запознавање на религиите" },
  {
    value: "Klasicna kultura vo evropskata civilizacija",
    label: "Класична култура во европската цивилизација",
  },
  { value: "Albanski jazik", label: "Албански јазик" },
];
